### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by jotdl** [akhikhl/wuff#105]
Hey there,

We are currently evaluating if we can switch from our maven based eclipse rcp product build to a gradle based one. As it seems the wuff plugin is the only mature gradle plugin for building eclipse products.

But it looks, due last commit is from Sep. 2015 and last issues are not handled, that this project is not maintained anymore... Am I right or is it just working and that's why nothing is changed?!

Cheers

**Comment by paulvi** [comment]
It still uses eclipse-luna-sr2 repository for downloads

Just got 1,5 GB of old binaries after trying first app https://github.com/akhikhl/wuff/wiki/Create-first-Equinox-app

![wuff_repo](https://cloud.githubusercontent.com/assets/1614482/14203510/05579782-f831-11e5-9f9e-18841b8c3059.png)

**Comment by petarov** [comment]
Well, it does work. That much I can say, because we use it in production. With the exception of some [manifest merging issues I had](https://github.com/akhikhl/wuff/pull/83), Wuff is quite a stable tool.

@paulvi 4.5 / Mars was [already added](https://github.com/akhikhl/wuff/blob/master/libs/wuff-plugin/src/main/resources/org/akhikhl/wuff/defaultConfig.groovy#L421), so you should be able to use it by explicitly specifying the following in your build.gradle

```
selectedEclipseVersion = '4.5'
```

**Comment by jotdl** [comment]
Ok, that's nice. I was not able to get it running with mars in our environment (p2 repository and so on) in the first place. But I will recheck that and create issues if necessary. Thanks for your anwsers @petarov and @paulvi.
